In [2]:
my_list = [1,2,3]


In [4]:
import numpy as np

In [6]:
np.array(my_list)

array([1, 2, 3])

In [8]:
my_mat =[[1,2,3],[4,5,6],[7,8,9]]

In [10]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
# auto generate an aarray
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
# steps
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [20]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [22]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [24]:
np.ones((4,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [27]:
np.linspace(0,5,100)

array([ 0.        ,  0.05050505,  0.1010101 ,  0.15151515,  0.2020202 ,
        0.25252525,  0.3030303 ,  0.35353535,  0.4040404 ,  0.45454545,
        0.50505051,  0.55555556,  0.60606061,  0.65656566,  0.70707071,
        0.75757576,  0.80808081,  0.85858586,  0.90909091,  0.95959596,
        1.01010101,  1.06060606,  1.11111111,  1.16161616,  1.21212121,
        1.26262626,  1.31313131,  1.36363636,  1.41414141,  1.46464646,
        1.51515152,  1.56565657,  1.61616162,  1.66666667,  1.71717172,
        1.76767677,  1.81818182,  1.86868687,  1.91919192,  1.96969697,
        2.02020202,  2.07070707,  2.12121212,  2.17171717,  2.22222222,
        2.27272727,  2.32323232,  2.37373737,  2.42424242,  2.47474747,
        2.52525253,  2.57575758,  2.62626263,  2.67676768,  2.72727273,
        2.77777778,  2.82828283,  2.87878788,  2.92929293,  2.97979798,
        3.03030303,  3.08080808,  3.13131313,  3.18181818,  3.23232323,
        3.28282828,  3.33333333,  3.38383838,  3.43434343,  3.48

In [29]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [32]:
np.random.rand(5)

array([ 0.79120618,  0.99596706,  0.62646946,  0.42075638,  0.09749473])

In [34]:
np.random.rand(5,2)

array([[ 0.90267236,  0.10244717],
       [ 0.13059821,  0.62349894],
       [ 0.04623855,  0.91138277],
       [ 0.84645623,  0.04940448],
       [ 0.64214257,  0.21719847]])

In [36]:
np.random.rand(5,5)

array([[ 0.30423261,  0.27843957,  0.80776283,  0.89160748,  0.66268518],
       [ 0.68337595,  0.4590072 ,  0.22778495,  0.93593761,  0.20583325],
       [ 0.87729993,  0.71920538,  0.0054054 ,  0.99177898,  0.3560291 ],
       [ 0.09222051,  0.22508789,  0.22459838,  0.0595665 ,  0.29870128],
       [ 0.28944906,  0.39234911,  0.01352755,  0.35476443,  0.53058773]])

In [38]:
np.random.randn(2)

array([-1.16178305,  0.80115668])

In [40]:
np.random.randn(2,5)

array([[ 1.27942679, -0.18603786, -0.29894017,  0.31292163,  1.0463247 ],
       [ 0.97690033, -0.71091059, -0.54131587,  0.57138014,  0.8708126 ]])

In [47]:
np.random.randint(1,100,30).reshape(2,15)

array([[37, 60,  9, 78, 74, 54, 18, 15, 33, 14, 40,  9, 44, 26, 24],
       [61, 23, 11, 99, 34, 66, 25, 26, 19, 75,  3, 62,  9, 71, 39]])

In [49]:
# creae two arrays
arr = np.arange(25)

In [52]:
ranarr = np.random.randint(0,50,10)
ranarr

array([44,  7, 27,  5, 45, 11, 27, 18, 48, 37])

In [57]:
max(ranarr)

48

In [59]:
ranarr.argmax()

8

In [62]:
ranarr.argmin()

3

In [64]:
ranarr.shape

(10,)

In [66]:
ranarr

array([44,  7, 27,  5, 45, 11, 27, 18, 48, 37])

In [71]:
ranarr = ranarr.reshape(2,5)

In [73]:
ranarr.shape

(2, 5)

In [75]:
arr.dtype

dtype('int32')

In [79]:
arr = np.arange(0,11)

In [82]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
arr[4]

4

In [86]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [94]:
arr[5:7]

array([5, 6])

In [96]:
arr2 = np.arange(11)

In [98]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
arr2[3:7] = 100

In [102]:
arr2

array([  0,   1,   2, 100, 100, 100, 100,   7,   8,   9,  10])

In [105]:
arr_2d = np.array([[5,10,15] ,[20,25,30],[35,40,45]])

In [107]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [114]:
arr_2d[:2][1:]

array([[20, 25, 30]])

In [115]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [124]:
arr_2d[:3,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [125]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [127]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [130]:
bool_arr = arr > 5

In [132]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True], dtype=bool)

In [134]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [136]:
arr[arr<3]

array([0, 1, 2])

In [138]:
arr_2d = np.arange(50).reshape(5,10)

In [140]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [143]:
# get all values starting from second row and getting all values after 3
arr_2d[1:3,2:]

array([[12, 13, 14, 15, 16, 17, 18, 19],
       [22, 23, 24, 25, 26, 27, 28, 29]])

In [145]:
arr_2d[1:,2:]

array([[12, 13, 14, 15, 16, 17, 18, 19],
       [22, 23, 24, 25, 26, 27, 28, 29],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47, 48, 49]])

In [149]:
arr_2d[3:,5:]

array([[35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49]])